title: Francesca Mastrogiuseppe
email: fran.mastrogiuseppe@gmail.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Researcher in Theoretical Neuroscience
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: --
github_username:  fmastrogiuseppe

# Build settings
theme: minima
#plugins:
#  - jekyll-feed

# Google analytics
#google_analytics: UA-190323600-1

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
